name: quiz_template
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  path_provider: ^2.1.1
  audioplayers: ^5.1.0
  localization: ^2.1.0
  images_picker: ^1.2.11
  file_picker: ^5.5.0
  google_mobile_ads: ^3.0.0
  restart_app: ^1.2.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  font_awesome_icon_class: ^0.0.6
  photo_view: ^0.14.0
  flutter_wallpaper_manager: ^0.0.4
  flutter_cache_manager: ^3.3.1
  http: ^1.1.0
  just_audio: ^0.9.35
  audio_service: ^0.18.12
  just_audio_background: ^0.0.1-beta.10
  audio_video_progress_bar: ^2.0.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/apps/
    - assets/sounds/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
